### ISSUE TITLE
Fix staging deployment automation

### ISSUE THREAD

**Issue by decimalator** [OregonDigital/OD2#1288]
### Descriptive summary

The update strategy for the `web` deployment is misconfigured. It needs to be updated to ensure that the service stays available during deployments.

### Expected behavior

Hitting the staging instance should not throw 5xx errors during a deployment.

### Accessibility Concerns

Add any information here to indicate any known or suspected accessibility issues for this ticket

**Comment by decimalator** [comment]
```
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
```

maxUnavailable needs to set to 0 while we have single replica deployments
